version: "2"

services:
  server:
    env_file:
      - .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - 5000:5000

    environment:

      FLASK_APP: src/server.py

      FLASK_DEBUG: 1

    command: vendor/bin/flask run --host=0.0.0.0

  dbdata:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
  db:
    image: postgres:9.4
    volumes_from:
      - dbdata

  testserver:
    env_file: .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
    image: postgres:9.4
