"""empty message

Revision ID: 36f7428cb71e
Revises: None
Create Date: 2019-06-20 14:59:16.341935

"""

# revision identifiers, used by Alembic.
revision = '36f7428cb71e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('genre', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('affiche', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=300), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('notation',
    sa.Column('username', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('note', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['movie.name'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('username', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notation')
    op.drop_table('user')
    op.drop_table('movie')
    # ### end Alembic commands ###
